# Generated by Django 2.2.2 on 2019-06-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutiesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('n_students', models.IntegerField(default=0)),
                ('n_rooms', models.IntegerField(default=0)),
                ('n_acs', models.IntegerField(default=0)),
                ('n_ds', models.IntegerField(default=0)),
                ('n_rs', models.IntegerField(default=0)),
                ('n_relief', models.IntegerField(default=0)),
                ('acs', models.CharField(max_length=500)),
                ('ds', models.CharField(max_length=500)),
                ('rs', models.CharField(max_length=500)),
                ('relief', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='priority',
        ),
        migrations.AddField(
            model_name='teacher',
            name='n_dates',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='n_am',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='n_duties',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='n_pm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='n_relief',
            field=models.IntegerField(default=0),
        ),
    ]
