# Generated by Django 2.2.2 on 2019-06-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutiesapp', '0002_auto_20190615_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='n_duties',
            field=models.IntegerField(default=1),
        ),
    ]
