# Generated by Django 2.2.2 on 2019-06-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutiesapp', '0003_auto_20190615_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='n_duties',
            field=models.IntegerField(default=0),
        ),
    ]
