# Generated by Django 2.2.2 on 2019-06-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutiesapp', '0004_auto_20190615_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='leaves',
            field=models.CharField(default='', max_length=50),
        ),
    ]
