# Generated by Django 2.2.2 on 2019-06-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutiesapp', '0005_teacher_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='n_dutiesassigned',
            field=models.IntegerField(default=0),
        ),
    ]
