# Generated by Django 2.2.2 on 2019-09-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutiesapp', '0006_teacher_n_dutiesassigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='n_dates',
            field=models.CharField(default='', max_length=500),
        ),
    ]
