# Generated by Django 2.2.2 on 2019-12-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutiesapp', '0007_auto_20190922_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Flag',
            field=models.IntegerField(default=0),
        ),
    ]
