# Generated by Django 2.2.2 on 2019-12-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutiesapp', '0008_teacher_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='leaves',
            field=models.CharField(default='', max_length=500),
        ),
    ]
