# Generated by Django 2.2.2 on 2019-12-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutiesapp', '0009_auto_20191224_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='leaves',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
